## Amazonデータセットの閲覧

```
$ sudo apt install git-lfs 
$ git clone https://github.com/amazon-science/esci-data.git
```

In [ ]:
import pandas as pd

df = pd.read_parquet(
    "esci-data/shopping_queries_dataset/shopping_queries_dataset_products.parquet", 
    filters=[("product_locale", "=", "jp")]
)
df.sample(n=5, random_state=0)

,product_id,product_title,product_description,product_bullet_point,product_brand,product_color,product_locale
178457,B07Z8LLPJ7,TAFLY シール 恐竜きょうりゅうシール ごほうびシール 生き物シール学校幼稚園保育園習シ...,多用途：<br> お手紙やメッセージカード、写真も華やかにデコレーションできるシールです。<...,ノートの整理、お手紙、メッセージカード作り、スクラップブッキング、プレゼントなどに…。\n一...,TAFLY,None,jp
221268,4086179083,ジョジョの奇妙な冒険 1~7巻(第1・2部)セット (集英社文庫(コミック版)),None,None,集英社,None,jp
116995,B01CPBVGLS,【輸入王オリジナル】時計パーツ ブライトリングと互換性あり Dバックル用 ベルト 型押しクロ...,高級時計の維持費の高さに悩んでいませんか？消耗品のパーツやメンテナンスで所有しているだけで維...,素材：カーフ※Dバックルは付属しません。 純正のDバックルにもお使いいただけます。\n時計側...,輸入王オリジナル,None,jp
289872,B000GPIDLC,ザ･ヴェルヴェット･ロープ･ツアー･ライブ [DVD],None,None,コロムビアミュージックエンタテインメント,None,jp
335136,B08R9YS3LT,NHK いないいないばあっ! ~ワンワン☆ダンス~〔CD〕,None,None,コロムビアミュージックエンタテインメント,None,jp

In [5]:

df.sample(n=5, random_state=0)

,product_id,product_title,product_description,product_bullet_point,product_brand,product_color,product_locale
178457,B07Z8LLPJ7,TAFLY シール 恐竜きょうりゅうシール ごほうびシール 生き物シール学校幼稚園保育園習シ...,多用途：<br> お手紙やメッセージカード、写真も華やかにデコレーションできるシールです。<...,ノートの整理、お手紙、メッセージカード作り、スクラップブッキング、プレゼントなどに…。\n一...,TAFLY,None,jp
221268,4086179083,ジョジョの奇妙な冒険 1~7巻(第1・2部)セット (集英社文庫(コミック版)),None,None,集英社,None,jp
116995,B01CPBVGLS,【輸入王オリジナル】時計パーツ ブライトリングと互換性あり Dバックル用 ベルト 型押しクロ...,高級時計の維持費の高さに悩んでいませんか？消耗品のパーツやメンテナンスで所有しているだけで維...,素材：カーフ※Dバックルは付属しません。 純正のDバックルにもお使いいただけます。\n時計側...,輸入王オリジナル,None,jp
289872,B000GPIDLC,ザ･ヴェルヴェット･ロープ･ツアー･ライブ [DVD],None,None,コロムビアミュージックエンタテインメント,None,jp
335136,B08R9YS3LT,NHK いないいないばあっ! ~ワンワン☆ダンス~〔CD〕,None,None,コロムビアミュージックエンタテインメント,None,jp

## OpenSearchへのデータ登録

In [1]:
import requests
import json
import pandas as pd

In [2]:

# OpenSearchの接続情報
BASE_URL = "http://localhost:9200"
INDEX_NAME = "amazon-jp"
HEADERS = {"Content-Type": "application/json"}

In [ ]:

mapping = {
    "mappings": {
        "properties": {
            "product_id": {"type": "keyword"},
            "product_title": {"type": "text"},
            "product_bullet_point": {"type": "text"},
            "product_description": {"type": "text"},
            "product_brand": {"type": "text"},
            "product_color_name": {"type": "text"},
            "product_locale": {"type": "keyword"}
        }
    }
}

response = requests.put(
    f"{BASE_URL}/{INDEX_NAME}", headers=HEADERS, data=json.dumps(mapping)
)
response.json()

In [3]:
response = requests.get(f"{BASE_URL}/{INDEX_NAME}/_mapping", headers=HEADERS)
response.json()

{'amazon-jp': {'mappings': {'properties': {'product_brand': {'type': 'text'},
    'product_bullet_point': {'type': 'text'},
    'product_color_name': {'type': 'text'},
    'product_description': {'type': 'text'},
    'product_id': {'type': 'keyword'},
    'product_locale': {'type': 'keyword'},
    'product_title': {'type': 'text'}}}}}